import React from "react";
import styled from "styled-components";

const StyledContainer = styled.div`
  width: 100%;
  height: 100%;
  margin: 0 auto;
  .container {
    margin: 0 2%;
    .heading {
      font-size: 1.7rem;
    }
    .sub-heading {
      font-size: 1.2rem;
    }
    .transport-method {
      font-size: 1.4rem;
      font-weight: bold;
      margin: 20px auto;
      text-align: center;
    }
  }
`;

class Dashboard extends React.Component {
  render() {
    return (
      <StyledContainer>
        <div className="container">
          <h1>Welcome to the app</h1>
          <div>
            <div className="heading">What is Carbon footprint?</div>
            <div>
              A carbon footprint is defined as: The total amount of greenhouse
              gases produced to directly and indirectly support human
              activities, usually expressed in equivalent tons of carbon dioxide
              (CO2). In other words: When you drive a car, the engine burns fuel
              which creates a certain amount of CO2, depending on its fuel
              consumption and the driving distance. (CO2 is the chemical symbol
              for carbon dioxide). When you heat your house with oil, gas or
              coal, then you also generate CO2. Even if you heat your house with
              electricity, the generation of the electrical power may also have
              emitted a certain amount of CO2. When you buy food and goods, the
              production of the food and goods also emitted some quantities of
              CO2.
            </div>
          </div>

          <div>
            <div className="heading"> EFFECTS OF CARBON FOOTPRINT </div>{" "}
            <div>
              Some of the major effects of carbon footprint are described below:
              <p>
                1) Greenhouse Gases Many human activities like electricity
                production and transportation results in the emission of green
                house gases like CO2 (Carbon di Oxide) resulting in the
                Greenhouse effect and an increase in Earth’s normal temperature.
                Transportation alone contributed to a 40% increase in the level
                of CO2, an important green house gas. And increase in the level
                of Green house gases result in the entrapment of heat on Earth,
                known as Green House effect. Many plastic production industries
                leave considerable amount of Carbon footprint, producing million
                of tons of Greenhouse gases into the Atmosphere.
              </p>{" "}
              <p>
                {" "}
                2) Climate Change Climate change is one of the major effects of
                leaving carbon footprint. Earth has a natural layer of Green
                house gases like, carbon di oxide, Methane, water vapor, Nitrous
                oxide, which help in maintaining Earth’s temperature by trapping
                UV rays from the Sun. The Greenhouse gases emanated from the
                factories or other transport related activities are most
                instrumental in changing the climate change as witnessed in the
                world today.{" "}
              </p>
              <p>
                3) Marine Life Depletion Carbon footprint generated by human
                activities has resulted in a considerable decrease in the Marine
                Life including sea Turtles, Dolphins, Whales etc. Ships of
                various sizes, whether used for fishing or transport leave some
                kind of footprint behind them, when sailing through deep waters.
                Sometimes huge sea liners are found to leave a trail of fuel and
                garbage in deep sea, which proves to be disastrous for life of
                marine animals.{" "}
              </p>{" "}
              <p>
                4) Depletion of Natural Resources Carbon footprint left by Human
                activities play a vital role in decreasing our natural resources
                and harming the environment. Every Human activity which leaves
                carbon foot print does its bit in the depletion of our natural
                resources. Activities like mining, results in erosion, formation
                of sink holes and contamination of soil and water, by the
                chemicals produced during the mining process. Apart from
                polluting soil and water it also results in deforestation,
                having an effect on ecological balance.Other profit oriented
                activities by Humans like factories, too play a vital role in
                the depletion of natural resources by leaving considerable
                amount of carbon footprint into the environment.
              </p>
            </div>
          </div>
          <div>
            <div className="heading">
              Ways to reduce personal carbon footprint
            </div>
            <div className="sub-heading">General Way</div>
            <div>
              The most common way to reduce the carbon footprint of humans is to
              Reduce, Reuse, Recycle, Refuse. This can also be done by using
              reusable items such as thermoses for daily coffee or plastic
              containers for water and other cold beverages rather than
              disposable ones. If that option isn't available, it is best to
              properly recycle the disposable items after use. When one
              household recycles at least half of their household waste, they
              can save 1.2 tons of carbon dioxide annually. Another easy option
              is to drive less. By walking or biking to the destination rather
              than driving, not only is a person going to save money on gas, but
              they will be burning less fuel and releasing fewer emissions into
              the atmosphere. However, if walking is not an option, one can look
              into carpooling or mass transportation options in their area.
              Another option for reducing the carbon footprint of humans is to
              use less air conditioning and heating in the home. By adding
              insulation to the walls and attic of one's home, and installing
              weather stripping or caulking around doors and windows one can
              lower their heating costs more than 25 percent.
            </div>
            <div className="sub-heading">Alternatives to driving</div>
            <div>
              When possible, walk or ride your bike in order to avoid carbon
              emissions completely. Carpooling and public transportation
              drastically reduce CO2 emissions by spreading them out over many
              riders. Drive a low carbon vehicle High mileage doesn’t always
              mean low CO2 emissions. All vehicles have an estimated
              miles-per-gallon rating. Electric cars emit no CO2 if they’re
              charged with clean electricity. If you don’t charge it with your
              home’s solar panels AND live somewhere like WY, MO, MO, WV, or KY
              you’re BETTER OFF with a hybrid or high-mileage gas/diesel car.
              Here’s why. After incentives and gas savings, it essentially costs
              nothing to switch to an electric car like the the Nissan Leaf. Get
              a hitch-mounted cargo rack Don’t buy a minivan or SUV if you don’t
              need 4WD and/or will only occasionally need the extra space. A
              receiver hitch and a rack like this one only cost a few hundred
              bucks. Avoid roof-top boxes, which cost much more, increase
              aerodynamic drag, and decrease fuel economy. Driving style
              Speeding and unnecessary acceleration reduce mileage by up to 33%,
              waste gas and money, and increase your carbon footprint. Tire
              inflation and other tuning Properly inflated tires improve your
              gas mileage by up to 3%. It also helps to use the correct grade of
              motor oil, and to keep your engine tuned, because some maintenance
              fixes, like fixing faulty oxygen sensors, can increase fuel
              efficiency by up to 40%. Avoid traffic Being stuck in traffic
              wastes gas and unneccessarily creates CO2. Use traffic websites
              and apps and go a different way or wait. Misc. Combine errands to
              make fewer trips. Remove excess weight from your car. Use cruise
              control.
            </div>
          </div>

          <div className="transport-method">You are travelling via: </div>
        </div>
      </StyledContainer>
    );
  }
}

export default Dashboard;
